import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :task_master, TaskMasterWeb.Endpoint,
  url: [
    host: System.get_env("RENDER_EXTERNAL_HOSTNAME") || "task-manager-g7rp.onrender.com",
    scheme: "https",
    port: 443
  ],
  check_origin: [
    "https://" <> (System.get_env("RENDER_EXTERNAL_HOSTNAME") || "task-manager-g7rp.onrender.com"),
    "http://localhost:4000" # Allow local development
  ],
  cache_static_manifest: "priv/static/cache_manifest.json",
  adapter: Bandit.PhoenixAdapter,
  render_errors: [
    formats: [html: TaskMasterWeb.ErrorHTML, json: TaskMasterWeb.ErrorJSON],
    layout: false
  ],
  pubsub_server: TaskMaster.PubSub,
  live_view: [signing_salt: "qubVAq85"]




# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: TaskMaster.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
